# Use Maven to build the project
FROM maven:3.9.9-eclipse-temurin-21 as builder
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Use a lighter image for the final build
FROM eclipse-temurin:21
WORKDIR /app
COPY --from=builder /app/target/Enrollement-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
